export interface IconItem {
  name: string;
  label: string;
  category: string;
  keywords: string[];
}

export interface IconCategory {
  id: string;
  label: string;
  icon: string;
}

export const ICON_CATEGORIES: IconCategory[] = [
  { id: 'all', label: 'All Icons', icon: 'grid' },
  { id: 'business', label: 'Business & Accounting', icon: 'briefcase-business' },
  { id: 'finance', label: 'Finance & Banking', icon: 'landmark' },
  { id: 'people', label: 'Persons & Roles', icon: 'users' },
  { id: 'nature', label: 'Fruits & Nature', icon: 'sprout' },
  { id: 'animals', label: 'Animals & Pets', icon: 'dog' },
  { id: 'food', label: 'Food & Dining', icon: 'utensils' },
  { id: 'shopping', label: 'Shopping & Retail', icon: 'shopping-cart' },
  { id: 'home', label: 'Property & Utilities', icon: 'building' },
  { id: 'transport', label: 'Transport & Fleet', icon: 'car' },
  { id: 'travel', label: 'Travel & Outdoor', icon: 'plane' },
  { id: 'tech', label: 'Tech & Media', icon: 'smartphone' },
  { id: 'health', label: 'Health & Fitness', icon: 'heart-pulse' },
  { id: 'work', label: 'Work & Education', icon: 'graduation-cap' },
  { id: 'lifestyle', label: 'Family & Lifestyle', icon: 'party-popper' },
  { id: 'symbols', label: 'Symbols & Shapes', icon: 'star' },
];

export const ICON_LIBRARY: IconItem[] = [
  // ==========================================
  // 1. BUSINESS & ACCOUNTING (65+ icons)
  // ==========================================
  { name: 'briefcase-business', label: 'Corporate Business', category: 'business', keywords: ['business', 'corporate', 'company', 'enterprise', 'portfolio'] },
  { name: 'briefcase', label: 'Operations & Management', category: 'business', keywords: ['office', 'work', 'job', 'administration', 'operations'] },
  { name: 'building', label: 'Company Headquarters', category: 'business', keywords: ['hq', 'office', 'branch', 'headquarters', 'corporate'] },
  { name: 'building-2', label: 'Commercial Tower', category: 'business', keywords: ['high-rise', 'firm', 'enterprise', 'institution'] },
  { name: 'factory', label: 'Plant & Manufacturing', category: 'business', keywords: ['manufacturing', 'production', 'assembly', 'industrial', 'plant'] },
  { name: 'warehouse', label: 'Warehouse & Depot', category: 'business', keywords: ['depot', 'storage', 'inventory', 'logistics', 'supply'] },
  { name: 'land-plot', label: 'Commercial Real Estate', category: 'business', keywords: ['land', 'plot', 'property', 'lot', 'development'] },
  { name: 'store', label: 'Storefront / POS', category: 'business', keywords: ['retail', 'shop', 'outlet', 'merchant', 'pos'] },
  { name: 'presentation', label: 'Pitch & Board Meeting', category: 'business', keywords: ['presentation', 'slide', 'pitch', 'board', 'seminar', 'webinar'] },
  { name: 'target', label: 'Business KPI & Targets', category: 'business', keywords: ['kpi', 'revenue target', 'milestone', 'goal', 'quota'] },
  { name: 'award', label: 'Recognition & Milestones', category: 'business', keywords: ['award', 'honor', 'distinction', 'achievement', 'certificate'] },
  { name: 'calculator', label: 'Accounting & Costing', category: 'business', keywords: ['accounting', 'bookkeeping', 'cpa', 'computation', 'audit', 'tax'] },
  { name: 'scale', label: 'Balance Sheet & Audit', category: 'business', keywords: ['balance', 'audit', 'compliance', 'justice', 'reconciliation'] },
  { name: 'scale-3d', label: 'Asset Valuation', category: 'business', keywords: ['valuation', 'equity', 'appraisal', 'assets', 'liabilities'] },
  { name: 'stamp', label: 'Official Seal & Permit', category: 'business', keywords: ['bir', 'dti', 'sec', 'stamp', 'permit', 'notarized', 'clearance'] },
  { name: 'receipt', label: 'Official Receipt', category: 'business', keywords: ['receipt', 'proof of payment', 'bill', 'expense', 'voucher'] },
  { name: 'receipt-text', label: 'Detailed Tax Invoice', category: 'business', keywords: ['invoice', 'tax', 'bir invoice', 'statement', 'billing'] },
  { name: 'receipt-cent', label: 'Petty Cash Voucher', category: 'business', keywords: ['petty cash', 'cents', 'micro reimbursement', 'small expense'] },
  { name: 'receipt-euro', label: 'EUR Invoice', category: 'business', keywords: ['euro invoice', 'international billing', 'foreign bill'] },
  { name: 'receipt-pound-sterling', label: 'GBP Invoice', category: 'business', keywords: ['pound invoice', 'uk billing', 'overseas invoice'] },
  { name: 'receipt-indian-rupee', label: 'INR Invoice', category: 'business', keywords: ['inr invoice', 'rupee billing', 'offshore invoice'] },
  { name: 'file-spreadsheet', label: 'General Ledger / Excel', category: 'business', keywords: ['excel', 'csv', 'ledger', 'spreadsheets', 'financial records'] },
  { name: 'file-chart-column', label: 'P&L Statement / Report', category: 'business', keywords: ['profit and loss', 'p&l', 'income statement', 'bar chart', 'report'] },
  { name: 'file-chart-line', label: 'Financial Forecast', category: 'business', keywords: ['projection', 'forecast', 'line chart', 'trends', 'outlook'] },
  { name: 'file-chart-pie', label: 'Expense Breakdown', category: 'business', keywords: ['pie chart', 'cost allocation', 'budget report', 'distribution'] },
  { name: 'file-text', label: 'Service Contract', category: 'business', keywords: ['contract', 'nda', 'agreement', 'terms', 'document'] },
  { name: 'file-check', label: 'Audited Filing', category: 'business', keywords: ['cleared', 'verified document', 'approved report', 'signed filing'] },
  { name: 'file-search', label: 'Due Diligence & Audit', category: 'business', keywords: ['inspection', 'tax investigation', 'audit review', 'records search'] },
  { name: 'file-stack', label: 'Invoice Archive', category: 'business', keywords: ['payables', 'receivables', 'documentation archive', 'records'] },
  { name: 'files', label: 'Corporate Records', category: 'business', keywords: ['filing', 'archives', 'bylaws', 'corporate documents'] },
  { name: 'signature', label: 'Executive Signature', category: 'business', keywords: ['sign-off', 'authorization', 'signature', 'director approval'] },
  { name: 'pen-line', label: 'Contract Endorsement', category: 'business', keywords: ['signing', 'endorsement', 'execution', 'deal close'] },
  { name: 'pen-tool', label: 'Creative & Design Services', category: 'business', keywords: ['agency', 'design contract', 'branding', 'graphics'] },
  { name: 'pencil-ruler', label: 'Engineering & Drafting', category: 'business', keywords: ['architecture', 'blueprint', 'technical drawing', 'drafting'] },
  { name: 'scroll', label: 'Charter & Constitution', category: 'business', keywords: ['charter', 'resolution', 'board resolution', 'founding doc'] },
  { name: 'scroll-text', label: 'Articles of Incorporation', category: 'business', keywords: ['sec registration', 'incorporation', 'legal statutes'] },
  { name: 'clipboard-check', label: 'Compliance Inspection', category: 'business', keywords: ['compliance', 'inspection', 'qc', 'quality control', 'internal audit'] },
  { name: 'clipboard-list', label: 'Inventory Stocktake', category: 'business', keywords: ['stocktake', 'manifest', 'supply list', 'requisition'] },
  { name: 'clipboard-pen-line', label: 'Purchase Order', category: 'business', keywords: ['po', 'purchase order', 'procurement', 'work order'] },
  { name: 'clipboard-clock', label: 'Timesheet & Billables', category: 'business', keywords: ['billable hours', 'time tracking', 'consulting log', 'timesheet'] },
  { name: 'wallet-cards', label: 'Corporate Cards', category: 'business', keywords: ['corporate card', 'company expense', 'business wallet'] },
  { name: 'wallet-minimal', label: 'Petty Cash Fund', category: 'business', keywords: ['cash box', 'operating fund', 'revolving fund'] },
  { name: 'banknote-check', label: 'Cleared Check / Payout', category: 'business', keywords: ['cheque', 'disbursement', 'cleared check', 'payroll payout'] },
  { name: 'badge-check', label: 'Accredited Supplier', category: 'business', keywords: ['accredited', 'verified vendor', 'kyc approved', 'cleared supplier'] },
  { name: 'trending-up', label: 'Revenue Growth', category: 'business', keywords: ['growth', 'profit increase', 'sales margin', 'expansion'] },
  { name: 'trending-down', label: 'Cost Reduction / Decline', category: 'business', keywords: ['expense reduction', 'loss', 'decline', 'drop'] },
  { name: 'trending-up-down', label: 'Cash Flow Volatility', category: 'business', keywords: ['fluctuation', 'flux', 'volatility', 'working capital'] },
  { name: 'chart-bar-big', label: 'Annual Revenue Graph', category: 'business', keywords: ['annual revenue', 'gross income', 'financial bar chart'] },
  { name: 'chart-column', label: 'Monthly Gross Margins', category: 'business', keywords: ['margins', 'ebitda', 'column chart', 'performance'] },
  { name: 'chart-gantt', label: 'Project Milestones', category: 'business', keywords: ['gantt', 'roadmap', 'deliverables', 'schedule timeline'] },
  { name: 'chart-spline', label: 'Growth Curve', category: 'business', keywords: ['s-curve', 'growth curve', 'traction', 'user growth'] },
  { name: 'goal', label: 'Strategic Milestone', category: 'business', keywords: ['goal', 'vision', 'objective', 'okr'] },
  { name: 'kanban', label: 'Project Workflow', category: 'business', keywords: ['kanban', 'scrum', 'tasks', 'pipeline', 'workflow'] },
  { name: 'square-kanban', label: 'Sprint Planning', category: 'business', keywords: ['sprint', 'backlog', 'agile', 'delivery'] },
  { name: 'folder-kanban', label: 'Client Accounts Folder', category: 'business', keywords: ['client dossier', 'project folder', 'engagement'] },
  { name: 'folder-archive', label: 'Fiscal Year Archive', category: 'business', keywords: ['tax archive', 'annual records', 'storage folder'] },
  { name: 'folder-sync', label: 'Branch Data Sync', category: 'business', keywords: ['branch reconciliation', 'multi-branch', 'synchronization'] },
  { name: 'folder-check', label: 'Closed Deal Archive', category: 'business', keywords: ['completed engagement', 'closed deal', 'archived case'] },
  { name: 'table-cells-merge', label: 'Consolidation & Merge', category: 'business', keywords: ['merger', 'consolidation', 'multi-company balance'] },
  { name: 'hourglass', label: 'Payment Terms (Net 30/60)', category: 'business', keywords: ['net 30', 'net 60', 'credit terms', 'accounts receivable'] },
  { name: 'timer', label: 'Hourly Billable Rate', category: 'business', keywords: ['retainer timer', 'billable rate', 'hourly fees'] },
  { name: 'calendar-range', label: 'Fiscal Accounting Period', category: 'business', keywords: ['fiscal quarter', 'calendar range', 'fiscal year', 'reporting cycle'] },
  { name: 'calendar-check', label: 'Tax Filing Deadline', category: 'business', keywords: ['tax return', 'bir deadline', 'quarterly filing', 'cleared date'] },
  { name: 'calendar-clock', label: 'Payroll Schedule', category: 'business', keywords: ['payday', 'payroll run', 'auto-debit schedule'] },
  { name: 'calendar-sync', label: 'Contract Renewal Date', category: 'business', keywords: ['annual renewal', 'retainer cycle', 'recurring agreement'] },
  { name: 'shield-check', label: 'Business Liability Insurance', category: 'business', keywords: ['insurance policy', 'commercial protection', 'general liability'] },
  { name: 'shield-user', label: 'D&O Liability Coverage', category: 'business', keywords: ['director insurance', 'officer cover', 'indemnity'] },
  { name: 'shield-alert', label: 'Compliance Audit Notice', category: 'business', keywords: ['audit warning', 'compliance breach', 'regulatory risk'] },
  { name: 'shield-lock', label: 'Trade Secrets & IP', category: 'business', keywords: ['ip protection', 'patent', 'trade secret', 'confidentiality'] },
  { name: 'truck', label: 'Freight & Fleet Logistics', category: 'business', keywords: ['fleet', 'freight', 'cargo delivery', 'haulage'] },
  { name: 'truck-electric', label: 'Eco Fleet Transport', category: 'business', keywords: ['green fleet', 'electric transport', 'sustainable delivery'] },
  { name: 'boxes', label: 'Inventory & Pallets', category: 'business', keywords: ['bulk goods', 'wholesale stock', 'warehouse inventory'] },
  { name: 'package', label: 'Order Fulfillment', category: 'business', keywords: ['order pack', 'dispatch', 'fulfillment', 'parcel'] },
  { name: 'package-check', label: 'Order Delivered & Cleared', category: 'business', keywords: ['pod', 'proof of delivery', 'goods accepted'] },
  { name: 'package-open', label: 'Unboxing & Inspection', category: 'business', keywords: ['qc check', 'goods received', 'incoming stock'] },
  { name: 'package-plus', label: 'Restock Requisition', category: 'business', keywords: ['restock', 'inflow', 'supply receipt'] },
  { name: 'package-search', label: 'Supply Chain Tracking', category: 'business', keywords: ['tracking', 'waybill', 'consignment search'] },
  { name: 'baggage-claim', label: 'Customs & Tariffs', category: 'business', keywords: ['import duty', 'customs clearance', 'tariffs', 'freight claim'] },
  { name: 'container', label: 'Cargo Shipping & Freight', category: 'business', keywords: ['shipping container', 'ocean freight', 'import export', 'customs', 'cargo'] },
  { name: 'forklift', label: 'Warehouse & Material Handling', category: 'business', keywords: ['forklift', 'material handling', 'pallet', 'depot machinery', 'loading'] },
  { name: 'tractor', label: 'Commercial Agriculture Equipment', category: 'business', keywords: ['tractor', 'agribusiness', 'farm machinery', 'harvest equipment'] },
  { name: 'gavel', label: 'Legal & Regulatory Compliance', category: 'business', keywords: ['legal', 'lawyer', 'attorney', 'court', 'compliance', 'sec', 'settlement', 'litigation'] },
  { name: 'philippine-peso', label: 'PHP Domestic Invoicing', category: 'business', keywords: ['peso', 'php', 'local billing', 'b2b payment', 'philippine peso', 'cash flow'] },
  { name: 'newspaper', label: 'Press & Public Relations', category: 'business', keywords: ['press release', 'news', 'media', 'pr agency', 'publications', 'investor relations'] },
  { name: 'megaphone', label: 'Marketing & Advertising', category: 'business', keywords: ['ad spend', 'campaign', 'marketing', 'promotion', 'outreach', 'branding'] },
  { name: 'printer', label: 'Office Supplies & Printing', category: 'business', keywords: ['printing', 'copy center', 'stationery', 'office equipment', 'hardware'] },
  { name: 'briefcase-medical', label: 'Healthcare Practice & Clinic', category: 'business', keywords: ['clinic', 'medical supplies', 'practice management', 'healthcare b2b'] },

  // ==========================================
  // 2. PERSONS & ROLES (35+ icons)
  // ==========================================
  { name: 'user', label: 'Individual / Proprietor', category: 'people', keywords: ['person', 'user', 'individual', 'sole proprietor', 'freelancer'] },
  { name: 'users', label: 'Team & Staff', category: 'people', keywords: ['staff', 'employees', 'crew', 'team', 'workforce', 'payroll'] },
  { name: 'users-round', label: 'Organization & Community', category: 'people', keywords: ['community', 'association', 'group', 'members'] },
  { name: 'user-round', label: 'User Profile', category: 'people', keywords: ['profile', 'account holder', 'identity'] },
  { name: 'circle-user', label: 'Account Holder', category: 'people', keywords: ['member', 'client profile', 'subscriber'] },
  { name: 'circle-user-round', label: 'Client Avatar', category: 'people', keywords: ['avatar', 'customer', 'client'] },
  { name: 'square-user', label: 'Contact Profile', category: 'people', keywords: ['directory', 'address card', 'contact'] },
  { name: 'square-user-round', label: 'Staff Avatar', category: 'people', keywords: ['personnel', 'colleague', 'team member'] },
  { name: 'user-check', label: 'Verified Client', category: 'people', keywords: ['kyc verified', 'approved client', 'active customer'] },
  { name: 'user-plus', label: 'Client Onboarding', category: 'people', keywords: ['new customer', 'sign up', 'hire', 'onboarding'] },
  { name: 'user-minus', label: 'Churn / Offboarding', category: 'people', keywords: ['resignation', 'offboarding', 'churn', 'departed'] },
  { name: 'user-pen', label: 'Account Manager', category: 'people', keywords: ['manager', 'editor', 'representative', 'custodian'] },
  { name: 'user-search', label: 'Recruitment & Talent', category: 'people', keywords: ['headhunting', 'hiring', 'talent search', 'recruitment'] },
  { name: 'user-shield', label: 'Compliance Officer', category: 'people', keywords: ['legal officer', 'security admin', 'auditor', 'protection'] },
  { name: 'user-star', label: 'VIP Client / Executive', category: 'people', keywords: ['vip', 'high net worth', 'key client', 'c-suite'] },
  { name: 'user-cog', label: 'System Administrator', category: 'people', keywords: ['admin', 'technician', 'support officer', 'superuser'] },
  { name: 'user-key', label: 'Authorized Signatory', category: 'people', keywords: ['signatory', 'bank representative', 'officer with access'] },
  { name: 'user-lock', label: 'Restricted User', category: 'people', keywords: ['locked account', 'restricted access', 'compliance hold'] },
  { name: 'person-standing', label: 'Sole Proprietorship', category: 'people', keywords: ['individual business', 'single owner', 'independent contractor'] },
  { name: 'baby', label: 'Dependent / Child', category: 'people', keywords: ['dependent', 'child', 'infant', 'allowance', 'pediatric'] },
  { name: 'contact', label: 'Business Contact', category: 'people', keywords: ['directory', 'client contact', 'rolodex'] },
  { name: 'contact-round', label: 'Vendor Directory', category: 'people', keywords: ['supplier list', 'vendor contacts', 'address book'] },
  { name: 'book-user', label: 'Customer Directory', category: 'people', keywords: ['crm', 'customer database', 'address list'] },
  { name: 'file-user', label: 'Personnel Dossier', category: 'people', keywords: ['hr file', 'resume', 'cv', 'employment record'] },
  { name: 'handshake', label: 'Partnership & Joint Venture', category: 'people', keywords: ['deal', 'partnership', 'agreement', 'b2b', 'collaborator'] },
  { name: 'heart-handshake', label: 'Client Care & Retention', category: 'people', keywords: ['customer support', 'client care', 'retention', 'csr'] },
  { name: 'hand-helping', label: 'Consultant & Advisor', category: 'people', keywords: ['mentor', 'advisor', 'consultant', 'guidance', 'assistance'] },
  { name: 'hand-coins', label: 'Salary & Compensation', category: 'people', keywords: ['payroll disbursement', 'wages', 'compensation', 'stipend'] },
  { name: 'crown', label: 'Founder & CEO', category: 'people', keywords: ['owner', 'managing director', 'founder', 'ceo', 'president'] },
  { name: 'id-card', label: 'Employee ID Badge', category: 'people', keywords: ['staff badge', 'id credential', 'security badge'] },
  { name: 'glasses', label: 'Auditor & Legal Counsel', category: 'people', keywords: ['lawyer', 'auditor', 'advisor', 'counsel'] },
  { name: 'graduation-cap', label: 'Professional Credential', category: 'people', keywords: ['degree', 'certification', 'training', 'education'] },
  { name: 'hard-hat', label: 'Site Engineer / Contractor', category: 'people', keywords: ['engineer', 'builder', 'contractor', 'foreman', 'safety officer', 'construction'] },
  { name: 'chef-hat', label: 'Head Chef / Culinary Lead', category: 'people', keywords: ['chef', 'kitchen manager', 'baker', 'restaurateur', 'culinary'] },
  { name: 'stethoscope', label: 'Doctor / Medical Professional', category: 'people', keywords: ['physician', 'doctor', 'specialist', 'practitioner', 'medic'] },
  { name: 'user-round-check', label: 'Verified Stakeholder / KYC', category: 'people', keywords: ['kyc', 'verified identity', 'board member', 'approved user'] },
  { name: 'user-round-plus', label: 'New Hire / Contractor', category: 'people', keywords: ['new staff', 'freelancer onboard', 'talent', 'hire'] },
  { name: 'user-round-minus', label: 'Separated Staff / Terminated', category: 'people', keywords: ['resignation', 'former employee', 'terminated', 'exit'] },
  { name: 'user-round-search', label: 'Executive Search & HR', category: 'people', keywords: ['recruiter', 'headhunter', 'talent acquisition', 'hr'] },
  { name: 'user-round-cog', label: 'CTO / Technical Lead', category: 'people', keywords: ['cto', 'engineering lead', 'tech officer', 'architect'] },
  { name: 'id-card-lanyard', label: 'Staff Pass & Lanyard', category: 'people', keywords: ['badge lanyard', 'visitor pass', 'credential', 'access badge'] },

  // ==========================================
  // 3. FRUITS & NATURE (45+ icons)
  // ==========================================
  { name: 'apple', label: 'Fresh Apple', category: 'nature', keywords: ['apple', 'fruit', 'healthy', 'orchard', 'produce'] },
  { name: 'banana', label: 'Banana', category: 'nature', keywords: ['banana', 'fruit', 'potassium', 'produce', 'tropical'] },
  { name: 'cherry', label: 'Cherry', category: 'nature', keywords: ['cherry', 'berry', 'fruit', 'sweet'] },
  { name: 'citrus', label: 'Citrus / Orange / Lemon', category: 'nature', keywords: ['citrus', 'lemon', 'orange', 'lime', 'vitamin'] },
  { name: 'grape', label: 'Grapes / Vineyard', category: 'nature', keywords: ['grape', 'vineyard', 'wine produce', 'fruit cluster'] },
  { name: 'carrot', label: 'Carrot & Root Produce', category: 'nature', keywords: ['carrot', 'vegetable', 'agriculture', 'produce'] },
  { name: 'salad', label: 'Organic Greens', category: 'nature', keywords: ['salad', 'lettuce', 'diet', 'organic', 'farm fresh'] },
  { name: 'bean', label: 'Beans & Coffee Crops', category: 'nature', keywords: ['coffee bean', 'legume', 'bean', 'crop', 'harvest'] },
  { name: 'nut', label: 'Nuts & Acorns', category: 'nature', keywords: ['nut', 'almond', 'walnut', 'seed', 'harvest'] },
  { name: 'wheat', label: 'Wheat & Grain Harvest', category: 'nature', keywords: ['grain', 'wheat', 'cereal', 'harvest', 'agriculture'] },
  { name: 'sprout', label: 'Sprout & Seedling', category: 'nature', keywords: ['seedling', 'nursery', 'sprout', 'growth', 'germination'] },
  { name: 'leaf', label: 'Leaf / Eco Environment', category: 'nature', keywords: ['leaf', 'eco', 'green', 'sustainable', 'environment'] },
  { name: 'leafy-green', label: 'Leafy Botanicals', category: 'nature', keywords: ['cabbage', 'herb', 'spinach', 'produce'] },
  { name: 'clover', label: 'Clover / Organic Pasture', category: 'nature', keywords: ['clover', 'lucky', 'pasture', 'organic farm'] },
  { name: 'tree-deciduous', label: 'Shade Tree', category: 'nature', keywords: ['tree', 'deciduous', 'park', 'nature', 'landscape'] },
  { name: 'tree-pine', label: 'Pine Tree / Mountain Flora', category: 'nature', keywords: ['pine', 'evergreen', 'forest', 'conifer'] },
  { name: 'tree-palm', label: 'Palm Tree / Tropical Coast', category: 'nature', keywords: ['palm', 'coconut', 'tropical', 'beach', 'resort'] },
  { name: 'trees', label: 'Forest & Woodlands', category: 'nature', keywords: ['woods', 'forest', 'timber', 'nature reserve'] },
  { name: 'flower', label: 'Flower / Florist', category: 'nature', keywords: ['blossom', 'petal', 'flower', 'gardening', 'floristry'] },
  { name: 'flower-2', label: 'Flora & Orchids', category: 'nature', keywords: ['orchid', 'botanical', 'exotic flower', 'ornamental'] },
  { name: 'sun', label: 'Sun / Solar Energy', category: 'nature', keywords: ['sun', 'sunlight', 'solar', 'sunny day'] },
  { name: 'sun-medium', label: 'Moderate Sunshine', category: 'nature', keywords: ['warmth', 'sunlight', 'daytime'] },
  { name: 'sun-dim', label: 'Gentle Sunlight', category: 'nature', keywords: ['diffused', 'dawn', 'dusk', 'soft sun'] },
  { name: 'sun-snow', label: 'Sun & Snow Climate', category: 'nature', keywords: ['alpine weather', 'winter sun', 'climate'] },
  { name: 'sun-moon', label: 'Day / Night Cycle', category: 'nature', keywords: ['diurnal', 'full day', 'orbit', 'astronomy'] },
  { name: 'moon', label: 'Crescent Moon', category: 'nature', keywords: ['night', 'lunar', 'evening', 'moonlight'] },
  { name: 'moon-star', label: 'Night Sky & Stars', category: 'nature', keywords: ['starlight', 'astronomy', 'nighttime'] },
  { name: 'cloud', label: 'Cloudy Sky', category: 'nature', keywords: ['overcast', 'cloud', 'atmosphere', 'weather'] },
  { name: 'cloud-rain', label: 'Rain & Precipitation', category: 'nature', keywords: ['rain', 'shower', 'monsoon', 'water cycle'] },
  { name: 'cloud-sun', label: 'Partly Cloudy', category: 'nature', keywords: ['fair weather', 'partly sunny', 'temperate'] },
  { name: 'cloud-sun-rain', label: 'Sun Shower', category: 'nature', keywords: ['intermittent rain', 'rainbow weather'] },
  { name: 'cloud-lightning', label: 'Thunder & Storm', category: 'nature', keywords: ['lightning', 'storm', 'cyclone', 'thunder'] },
  { name: 'cloud-fog', label: 'Fog & Mist', category: 'nature', keywords: ['fog', 'haze', 'mist', 'visibility'] },
  { name: 'cloud-snow', label: 'Snow Flurries', category: 'nature', keywords: ['blizzard', 'snowfall', 'chilly', 'frost'] },
  { name: 'cloud-hail', label: 'Hailstorm Weather', category: 'nature', keywords: ['hail', 'severe weather', 'ice stones'] },
  { name: 'cloud-drizzle', label: 'Light Drizzle', category: 'nature', keywords: ['sprinkle', 'drizzle', 'misty rain'] },
  { name: 'snowflake', label: 'Snowflake / Cold Chain', category: 'nature', keywords: ['ice', 'freeze', 'snowflake', 'cold storage'] },
  { name: 'rainbow', label: 'Rainbow', category: 'nature', keywords: ['rainbow', 'spectrum', 'clear skies', 'prism'] },
  { name: 'flame', label: 'Flame / Biofuel', category: 'nature', keywords: ['fire', 'flame', 'heat', 'combustion', 'thermal'] },
  { name: 'wind', label: 'Wind / Airflow', category: 'nature', keywords: ['breeze', 'wind turbine', 'air', 'ventilation'] },
  { name: 'mountain', label: 'Mountain & Summit', category: 'nature', keywords: ['peak', 'ridge', 'mountain', 'elevation', 'altitude'] },
  { name: 'mountain-snow', label: 'Glacier & Snowy Peak', category: 'nature', keywords: ['glacier', 'snow peak', 'alps', 'sub-zero'] },
  { name: 'broccoli', label: 'Broccoli & Farm Produce', category: 'nature', keywords: ['broccoli', 'vegetables', 'produce', 'greens', 'agriculture'] },
  { name: 'hop', label: 'Hops & Botanical Crops', category: 'nature', keywords: ['hop', 'brewery crop', 'botanical', 'flora'] },
  { name: 'cannabis', label: 'Hemp & Commercial Botanicals', category: 'nature', keywords: ['hemp', 'cbd', 'botanicals', 'herbal', 'plants'] },
  { name: 'earth', label: 'Earth & Global ESG', category: 'nature', keywords: ['esg', 'environment', 'planet', 'sustainable earth', 'ecology'] },
  { name: 'sunrise', label: 'Sunrise & Early Harvest', category: 'nature', keywords: ['sunrise', 'morning', 'early start', 'field dawn', 'daybreak'] },
  { name: 'waves', label: 'Coastal Waters & Marine', category: 'nature', keywords: ['ocean', 'marine', 'sea', 'aquaculture waters', 'coastal'] },

  // ==========================================
  // 4. ANIMALS & PETS (20+ icons)
  // ==========================================
  { name: 'dog', label: 'Dog / Canine Care', category: 'animals', keywords: ['canine', 'puppy', 'dog', 'pet care', 'vet'] },
  { name: 'cat', label: 'Cat / Feline', category: 'animals', keywords: ['kitten', 'feline', 'cat', 'pet food', 'whisker'] },
  { name: 'bird', label: 'Bird / Poultry', category: 'animals', keywords: ['avian', 'bird', 'aviary', 'flight', 'feather'] },
  { name: 'fish', label: 'Fish / Aquaculture', category: 'animals', keywords: ['aquaculture', 'fishery', 'marine', 'fish pond'] },
  { name: 'rabbit', label: 'Rabbit / Bunny', category: 'animals', keywords: ['rabbit', 'bunny', 'hare', 'pet'] },
  { name: 'snail', label: 'Snail / Slow Pace', category: 'animals', keywords: ['snail', 'escargot', 'shell', 'slow'] },
  { name: 'turtle', label: 'Turtle / Longevity', category: 'animals', keywords: ['turtle', 'tortoise', 'marine life', 'longevity'] },
  { name: 'squirrel', label: 'Squirrel / Savings Instinct', category: 'animals', keywords: ['squirrel', 'acorn', 'forage', 'stockpile'] },
  { name: 'worm', label: 'Vermiculture / Earthworm', category: 'animals', keywords: ['compost', 'soil biology', 'earthworm'] },
  { name: 'bug', label: 'Bug & Pest Control', category: 'animals', keywords: ['insect', 'beetle', 'fumigation', 'pest management'] },
  { name: 'paw-print', label: 'Paw Print / Pet Shop', category: 'animals', keywords: ['veterinary', 'pet shop', 'grooming', 'animal shelter'] },
  { name: 'bone', label: 'Pet Nutrition & Treats', category: 'animals', keywords: ['bone', 'pet snacks', 'canine chew'] },
  { name: 'feather', label: 'Avian Feather', category: 'animals', keywords: ['quill', 'plume', 'feather', 'poultry'] },
  { name: 'egg', label: 'Egg / Farm Fresh', category: 'animals', keywords: ['poultry farm', 'egg production', 'organic egg'] },
  { name: 'egg-fried', label: 'Egg Breakfast', category: 'animals', keywords: ['fried egg', 'breakfast', 'culinary'] },
  { name: 'beef', label: 'Livestock & Cattle', category: 'animals', keywords: ['cattle', 'meat production', 'butcher', 'ranch', 'livestock'] },
  { name: 'shrimp', label: 'Shrimp & Prawn Fishery', category: 'animals', keywords: ['shrimp', 'prawn', 'crustacean', 'seafood aquaculture', 'marine'] },
  { name: 'fish-symbol', label: 'Commercial Fisheries', category: 'animals', keywords: ['marine biology', 'commercial fishing', 'catch', 'fish symbol'] },
  { name: 'panda', label: 'Wildlife & Conservation', category: 'animals', keywords: ['panda', 'endangered', 'wildlife fund', 'zoo', 'animals'] },
  { name: 'rat', label: 'Lab Research & Pest Control', category: 'animals', keywords: ['mouse', 'rodent', 'lab research', 'pest extermination'] },

  // ==========================================
  // 5. FINANCE & BANKING (40+ icons)
  // ==========================================
  { name: 'landmark', label: 'Central Bank', category: 'finance', keywords: ['institution', 'bank', 'monetary', 'treasury'] },
  { name: 'wallet', label: 'Primary Cash Wallet', category: 'finance', keywords: ['pocket money', 'cash wallet', 'funds'] },
  { name: 'banknote', label: 'Currency Banknote', category: 'finance', keywords: ['paper bills', 'cash', 'money', 'liquidity'] },
  { name: 'coins', label: 'Coin Reserves', category: 'finance', keywords: ['change', 'coins', 'cents', 'specie'] },
  { name: 'credit-card', label: 'Credit & Debit Card', category: 'finance', keywords: ['visa', 'mastercard', 'pos card', 'charge card'] },
  { name: 'piggy-bank', label: 'Savings Deposit', category: 'finance', keywords: ['savings', 'emergency stash', 'nest egg'] },
  { name: 'circle-dollar-sign', label: 'Dollar Coin Asset', category: 'finance', keywords: ['usd', 'dollar', 'fiat', 'reserve'] },
  { name: 'badge-dollar-sign', label: 'Cashback & Dividend', category: 'finance', keywords: ['dividend', 'cash reward', 'bonus'] },
  { name: 'badge-cent', label: 'Interest Accrual', category: 'finance', keywords: ['yield', 'cents', 'micro interest'] },
  { name: 'badge-euro', label: 'Euro Currency Account', category: 'finance', keywords: ['eur', 'forex euro', 'european currency'] },
  { name: 'badge-percent', label: 'APY & Interest Rate', category: 'finance', keywords: ['rate', 'yield', 'apr', 'compounding'] },
  { name: 'circle-percent', label: 'Percentage Ratio', category: 'finance', keywords: ['allocation', 'ratio', 'percent rate'] },
  { name: 'circle-euro', label: 'Euro Coin', category: 'finance', keywords: ['euro', 'european funds'] },
  { name: 'dollar-sign', label: 'Dollar Currency', category: 'finance', keywords: ['income', 'cash revenue', 'dollar'] },
  { name: 'euro', label: 'Euro Symbol', category: 'finance', keywords: ['forex', 'eur', 'europe'] },
  { name: 'pound-sterling', label: 'British Pound', category: 'finance', keywords: ['gbp', 'sterling', 'uk currency'] },
  { name: 'bitcoin', label: 'Crypto & Bitcoin', category: 'finance', keywords: ['btc', 'crypto', 'blockchain', 'digital asset'] },
  { name: 'vault', label: 'Safe Deposit Box', category: 'finance', keywords: ['vault', 'lockbox', 'security storage', 'reserves'] },
  { name: 'gem', label: 'Precious Commodities', category: 'finance', keywords: ['jewelry', 'diamonds', 'gold', 'precious gems'] },
  { name: 'chart-pie', label: 'Portfolio Allocation', category: 'finance', keywords: ['breakdown', 'asset allocation', 'pie chart'] },
  { name: 'chart-bar', label: 'Spending Trends', category: 'finance', keywords: ['budget bars', 'spending statistics'] },
  { name: 'chart-line', label: 'Investment Valuation', category: 'finance', keywords: ['stocks', 'equity performance', 'portfolio growth'] },
  { name: 'chart-candlestick', label: 'Market Trading', category: 'finance', keywords: ['forex', 'day trading', 'candlesticks', 'stock market'] },
  { name: 'arrow-left-right', label: 'Inter-Account Transfer', category: 'finance', keywords: ['wire', 'transfer', 'funds movement', 'move money'] },
  { name: 'arrow-down-left', label: 'Inflow / Deposit', category: 'finance', keywords: ['deposit', 'remittance in', 'credit'] },
  { name: 'arrow-up-right', label: 'Outflow / Withdrawal', category: 'finance', keywords: ['withdrawal', 'payment', 'debit'] },
  { name: 'scan-barcode', label: 'Barcode Utility Bill', category: 'finance', keywords: ['utility bill payment', 'barcode slip'] },
  { name: 'qr-code', label: 'QR Fast Payment', category: 'finance', keywords: ['instapay', 'pesonet', 'maya', 'gcash', 'qr payment'] },
  { name: 'send', label: 'Remittance Wire', category: 'finance', keywords: ['wire transfer', 'payout', 'western union'] },
  { name: 'percent', label: 'Tax & Markup Rate', category: 'finance', keywords: ['vat', 'withholding', 'markup'] },
  { name: 'split', label: 'Expense Splitting', category: 'finance', keywords: ['shared cost', 'split bill', 'reimbursement'] },

  // ==========================================
  // 6. FOOD & DINING (30+ icons)
  // ==========================================
  { name: 'utensils', label: 'Dining & Restaurants', category: 'food', keywords: ['restaurant', 'dining', 'lunch', 'dinner', 'eats'] },
  { name: 'utensils-crossed', label: 'Fine Dining', category: 'food', keywords: ['gourmet', 'cutlery', 'banquet', 'feast'] },
  { name: 'coffee', label: 'Cafe & Espresso', category: 'food', keywords: ['coffee', 'starbucks', 'espresso', 'tea', 'cafe'] },
  { name: 'cup-soda', label: 'Beverages & Boba', category: 'food', keywords: ['soft drink', 'juice', 'milk tea', 'refreshment'] },
  { name: 'pizza', label: 'Pizza & Fastfood', category: 'food', keywords: ['fastfood', 'snack', 'delivery', 'pizza'] },
  { name: 'beer', label: 'Pub & Craft Beer', category: 'food', keywords: ['brewery', 'pub', 'beer', 'bar'] },
  { name: 'wine', label: 'Wine Cellar & Lounge', category: 'food', keywords: ['cocktail', 'sommelier', 'wine', 'spirits'] },
  { name: 'cake', label: 'Bakery & Celebrations', category: 'food', keywords: ['birthday cake', 'pastry', 'patisserie'] },
  { name: 'cake-slice', label: 'Dessert Slice', category: 'food', keywords: ['pie', 'dessert', 'cheesecake', 'sweet'] },
  { name: 'cookie', label: 'Snacks & Confectionery', category: 'food', keywords: ['cookies', 'biscuit', 'treat', 'snack'] },
  { name: 'candy', label: 'Candy & Sweets', category: 'food', keywords: ['sugar', 'candies', 'treats'] },
  { name: 'candy-cane', label: 'Seasonal Confections', category: 'food', keywords: ['holiday sweets', 'candy cane'] },
  { name: 'popcorn', label: 'Cinema Snacks', category: 'food', keywords: ['popcorn', 'theater snack', 'munchies'] },
  { name: 'croissant', label: 'Pastry & Breakfast', category: 'food', keywords: ['croissant', 'danish', 'continental breakfast'] },
  { name: 'sandwich', label: 'Sandwich & Deli', category: 'food', keywords: ['burger', 'sandwich', 'quick lunch', 'deli'] },
  { name: 'soup', label: 'Hot Noodles & Broth', category: 'food', keywords: ['ramen', 'noodles', 'soup', 'stew'] },
  { name: 'ice-cream-cone', label: 'Ice Cream', category: 'food', keywords: ['gelato', 'sorbet', 'ice cream'] },
  { name: 'ice-cream-bowl', label: 'Sundae Dessert', category: 'food', keywords: ['dessert bowl', 'sundae', 'parfait'] },
  { name: 'drumstick', label: 'Poultry & Fried Chicken', category: 'food', keywords: ['fried chicken', 'poultry', 'chicken meal'] },
  { name: 'milk', label: 'Dairy & Milk Supply', category: 'food', keywords: ['milk', 'dairy', 'cream', 'fresh milk'] },
  { name: 'martini', label: 'Cocktail Bar', category: 'food', keywords: ['cocktail', 'martini', 'lounge bar'] },
  { name: 'glass-water', label: 'Mineral Water & Drinks', category: 'food', keywords: ['water', 'hydration', 'mineral water'] },
  { name: 'cooking-pot', label: 'Catering & Home Cooking', category: 'food', keywords: ['catering', 'meal prep', 'stew', 'cooking'] },
  { name: 'refrigerator', label: 'Kitchen Storage', category: 'food', keywords: ['fridge', 'pantry', 'groceries'] },
  { name: 'microwave', label: 'Pantry Appliances', category: 'food', keywords: ['reheat', 'convenience meal'] },

  // ==========================================
  // 7. SHOPPING & RETAIL (25+ icons)
  // ==========================================
  { name: 'shopping-cart', label: 'Supermarket Cart', category: 'shopping', keywords: ['groceries', 'cart', 'supermarket', 'mall'] },
  { name: 'shopping-bag', label: 'Shopping Bag', category: 'shopping', keywords: ['boutique', 'fashion haul', 'retail'] },
  { name: 'shopping-basket', label: 'Quick Buy Basket', category: 'shopping', keywords: ['convenience store', 'basket', 'mart'] },
  { name: 'tag', label: 'Promotional Tag', category: 'shopping', keywords: ['sale', 'discount', 'bargain', 'clearance'] },
  { name: 'tags', label: 'Multiple Categories Tag', category: 'shopping', keywords: ['catalog', 'classifications', 'tags'] },
  { name: 'gift', label: 'Gift & Corporate Giveaways', category: 'shopping', keywords: ['present', 'giveaway', 'birthday gift'] },
  { name: 'sparkles', label: 'Beauty & Cosmetics', category: 'shopping', keywords: ['skincare', 'perfume', 'luxury goods'] },
  { name: 'shirt', label: 'Apparel & Uniforms', category: 'shopping', keywords: ['clothing', 'workwear', 'wardrobe', 'shirt'] },
  { name: 'watch', label: 'Timepieces & Luxury', category: 'shopping', keywords: ['watch', 'luxury watch', 'accessory'] },
  { name: 'footprints', label: 'Footwear & Safety Shoes', category: 'shopping', keywords: ['shoes', 'sneakers', 'boots', 'safety boots'] },
  { name: 'scissors', label: 'Salon & Grooming', category: 'shopping', keywords: ['barbershop', 'haircut', 'salon', 'scissors'] },
  { name: 'barcode', label: 'Inventory Barcode', category: 'shopping', keywords: ['retail code', 'upc', 'stock code'] },
  { name: 'scan', label: 'Point of Sale Scan', category: 'shopping', keywords: ['scanner', 'pos reading'] },
  { name: 'ticket', label: 'Coupons & Vouchers', category: 'shopping', keywords: ['voucher', 'promo ticket', 'event pass'] },
  { name: 'box', label: 'Supply Box', category: 'shopping', keywords: ['package box', 'merchandise', 'carton'] },

  // ==========================================
  // 8. PROPERTY & UTILITIES (25+ icons)
  // ==========================================
  { name: 'home', label: 'Residential Property', category: 'home', keywords: ['house', 'home', 'mortgage', 'residential', 'rent'] },
  { name: 'bed', label: 'Furnishing & Suites', category: 'home', keywords: ['interior', 'bedroom', 'mattress', 'furniture'] },
  { name: 'sofa', label: 'Office Lounge / Furniture', category: 'home', keywords: ['sofa', 'reception', 'interior fitout'] },
  { name: 'bath', label: 'Sanitation Facilities', category: 'home', keywords: ['restroom', 'washroom', 'tub'] },
  { name: 'door-closed', label: 'Facility Access', category: 'home', keywords: ['office door', 'entry', 'access control'] },
  { name: 'key', label: 'Property Lease & Keys', category: 'home', keywords: ['tenancy', 'landlord', 'key handover', 'lease'] },
  { name: 'key-round', label: 'Access Key Card', category: 'home', keywords: ['keycard', 'master key', 'fob'] },
  { name: 'lock', label: 'Premises Security', category: 'home', keywords: ['safeguard', 'perimeter security', 'lock'] },
  { name: 'lightbulb', label: 'Electric Power Bill', category: 'home', keywords: ['electricity', 'meralco', 'power bill', 'energy'] },
  { name: 'lamp', label: 'Office Fixtures', category: 'home', keywords: ['lighting', 'interior lamp', 'fixtures'] },
  { name: 'tv', label: 'Conference Displays', category: 'home', keywords: ['monitor tv', 'av system', 'cable tv'] },
  { name: 'wifi', label: 'Broadband & Fiber', category: 'home', keywords: ['internet', 'fiber', 'pldt', 'converge', 'wifi router'] },
  { name: 'plug', label: 'Power Consumption', category: 'home', keywords: ['appliances', 'power outlet', 'wattage'] },
  { name: 'zap', label: 'Energy Utility', category: 'home', keywords: ['utility bill', 'power grid', 'voltage'] },
  { name: 'battery', label: 'Solar & Inverter Storage', category: 'home', keywords: ['solar battery', 'backup generator', 'inverter'] },
  { name: 'droplet', label: 'Water Utility Services', category: 'home', keywords: ['water bill', 'maynilad', 'manila water', 'waterworks'] },
  { name: 'droplets', label: 'Sanitation Utilities', category: 'home', keywords: ['cleaning water', 'sewerage'] },
  { name: 'air-vent', label: 'HVAC Air Conditioning', category: 'home', keywords: ['aircon', 'cooling', 'hvac', 'ventilation'] },
  { name: 'thermometer', label: 'Thermostat Control', category: 'home', keywords: ['temperature', 'climate', 'thermostat'] },
  { name: 'paint-bucket', label: 'Renovations & Fitouts', category: 'home', keywords: ['painting', 'decor', 'contractor fitout'] },
  { name: 'brush', label: 'Janitorial & Cleaning', category: 'home', keywords: ['housekeeping', 'maid service', 'janitorial'] },
  { name: 'hammer', label: 'Facility Maintenance', category: 'home', keywords: ['repairs', 'handyman', 'carpentry'] },
  { name: 'wrench', label: 'Plumbing & Mechanicals', category: 'home', keywords: ['plumbing repair', 'toolkit', 'pipefix'] },
  { name: 'trash-2', label: 'Waste Disposal Dues', category: 'home', keywords: ['garbage collection', 'waste management', 'hoa dues'] },
  { name: 'recycle', label: 'Waste Sorting & Eco', category: 'home', keywords: ['recycling', 'waste sorting', 'sustainability'] },

  // ==========================================
  // 9. TRANSPORT & FLEET (20+ icons)
  // ==========================================
  { name: 'car', label: 'Executive Car / Auto', category: 'transport', keywords: ['sedan', 'auto loan', 'company car', 'vehicle'] },
  { name: 'car-front', label: 'Car Front & Insurance', category: 'transport', keywords: ['auto insurance', 'pms registration', 'chassis'] },
  { name: 'car-taxi-front', label: 'Grab / Taxi Dispatch', category: 'transport', keywords: ['grab', 'taxi', 'ride-hailing', 'commute'] },
  { name: 'bus', label: 'Staff Bus & Commute', category: 'transport', keywords: ['shuttle', 'transit', 'bus fare'] },
  { name: 'train', label: 'Subway & Rail Commute', category: 'transport', keywords: ['mrt', 'lrt', 'rail', 'beep card'] },
  { name: 'bike', label: 'Courier Bicycle', category: 'transport', keywords: ['cycling', 'messenger bike', 'green transport'] },
  { name: 'fuel', label: 'Fuel & Petroleum', category: 'transport', keywords: ['gasoline', 'diesel', 'shell', 'petron', 'fleet fuel'] },
  { name: 'gauge', label: 'Fleet Mileage & PMS', category: 'transport', keywords: ['odometer', 'mileage', 'periodic maintenance'] },
  { name: 'navigation', label: 'GPS Logistics Routing', category: 'transport', keywords: ['maps', 'route navigation', 'toll routes'] },
  { name: 'parking-circle', label: 'Commercial Parking', category: 'transport', keywords: ['parking fees', 'valet ticket', 'mall parking'] },
  { name: 'parking-square', label: 'Reserved Office Bay', category: 'transport', keywords: ['parking bay', 'garage slot', 'reserved slot'] },
  { name: 'caravan', label: 'Executive Van & Shuttle', category: 'transport', keywords: ['van', 'shuttle service', 'uv express'] },

  // ==========================================
  // 10. TRAVEL & OUTDOOR (20+ icons)
  // ==========================================
  { name: 'plane', label: 'Commercial Flights', category: 'travel', keywords: ['airline', 'business travel', 'airfare', 'tickets'] },
  { name: 'plane-takeoff', label: 'Outbound Flight', category: 'travel', keywords: ['departure', 'overseas flight', 'trip takeoff'] },
  { name: 'plane-landing', label: 'Return Arrival', category: 'travel', keywords: ['landing', 'arrival', 'itinerary finish'] },
  { name: 'luggage', label: 'Business Travel Luggage', category: 'travel', keywords: ['baggage', 'suitcase', 'travel gear'] },
  { name: 'hotel', label: 'Hotel & Hospitality', category: 'travel', keywords: ['lodging', 'hotel booking', 'resort stay'] },
  { name: 'palmtree', label: 'Tropical Vacation', category: 'travel', keywords: ['resort', 'beach holiday', 'boracay', 'palawan'] },
  { name: 'sunset', label: 'Sightseeing Tour', category: 'travel', keywords: ['sunset', 'tourism', 'sightseeing'] },
  { name: 'tent', label: 'Glamping & Outdoor', category: 'travel', keywords: ['camping', 'outdoor retreat', 'glamping'] },
  { name: 'compass', label: 'Travel Guidance', category: 'travel', keywords: ['expedition', 'direction', 'explore'] },
  { name: 'map', label: 'Trip Itinerary Map', category: 'travel', keywords: ['route map', 'travel planner'] },
  { name: 'map-pin', label: 'Destination Geolocation', category: 'travel', keywords: ['location pin', 'check-in', 'branch address'] },
  { name: 'globe', label: 'Global Enterprise / Travel', category: 'travel', keywords: ['international', 'overseas market', 'global'] },
  { name: 'camera', label: 'Event Photography', category: 'travel', keywords: ['photos', 'camera equipment', 'media shoot'] },
  { name: 'ship', label: 'Maritime Logistics & Ferry', category: 'travel', keywords: ['cargo ship', 'ferry', 'cruise'] },
  { name: 'sailboat', label: 'Yacht Charter', category: 'travel', keywords: ['yacht', 'sailing', 'charter boat'] },
  { name: 'anchor', label: 'Harbor & Port Dues', category: 'travel', keywords: ['port fees', 'dockage', 'berth'] },
  { name: 'waves', label: 'Seaside & Waters', category: 'travel', keywords: ['ocean', 'marine', 'coastal'] },
  { name: 'backpack', label: 'Field Backpack', category: 'travel', keywords: ['gear backpack', 'fieldwork'] },

  // ==========================================
  // 11. TECH & MEDIA (20+ icons)
  // ==========================================
  { name: 'smartphone', label: 'Smartphone & Postpaid', category: 'tech', keywords: ['mobile', 'iphone', 'postpaid plan', 'device'] },
  { name: 'tablet', label: 'Tablet & Stylus', category: 'tech', keywords: ['ipad', 'pos tablet', 'drawing tablet'] },
  { name: 'laptop', label: 'Workstation Laptop', category: 'tech', keywords: ['macbook', 'laptop', 'notebook', 'workstation'] },
  { name: 'monitor', label: 'Desktop Monitor', category: 'tech', keywords: ['workstation screen', 'display', 'pc desktop'] },
  { name: 'hard-drive', label: 'Local Backup & SSD', category: 'tech', keywords: ['external drive', 'nas', 'ssd backup'] },
  { name: 'database', label: 'Cloud DB & Storage', category: 'tech', keywords: ['database', 'server hosting', 'aws storage'] },
  { name: 'server', label: 'On-Premise Server', category: 'tech', keywords: ['data center', 'rack server', 'sysadmin'] },
  { name: 'cloud', label: 'Cloud Infrastructure', category: 'tech', keywords: ['saas cloud', 'google drive', 'cloud subscriptions'] },
  { name: 'headphones', label: 'Audio Headsets', category: 'tech', keywords: ['call center headset', 'audio equipment'] },
  { name: 'mic', label: 'Broadcast & Podcasting', category: 'tech', keywords: ['microphone', 'studio mic', 'recording'] },
  { name: 'video', label: 'Video Conferencing', category: 'tech', keywords: ['zoom', 'teams meeting', 'video streaming'] },
  { name: 'film', label: 'Commercial Media', category: 'tech', keywords: ['video production', 'film production'] },
  { name: 'gamepad', label: 'Interactive & Gaming', category: 'tech', keywords: ['entertainment', 'gaming'] },
  { name: 'bot', label: 'AI Subscriptions', category: 'tech', keywords: ['chatgpt', 'claude', 'copilot', 'automation api'] },
  { name: 'code', label: 'Software Licenses & IDE', category: 'tech', keywords: ['github', 'saas tools', 'dev software'] },
  { name: 'terminal', label: 'DevOps & Tooling', category: 'tech', keywords: ['command line', 'linux server', 'hosting'] },
  { name: 'fingerprint', label: 'Biometric Access', category: 'tech', keywords: ['biometrics', 'fingerprint scanner', 'time clock'] },
  { name: 'cable', label: 'IT Cabling & Adapters', category: 'tech', keywords: ['network cables', 'hdmi', 'chargers'] },
  { name: 'battery-full', label: 'UPS & Power Bank', category: 'tech', keywords: ['backup battery', 'powerbank'] },

  // ==========================================
  // 12. HEALTH & WELLNESS (15+ icons)
  // ==========================================
  { name: 'heart-pulse', label: 'HMO & Healthcare', category: 'health', keywords: ['hmo', 'health card', 'medical clinic', 'hospital'] },
  { name: 'heart', label: 'Wellness Program', category: 'health', keywords: ['vitality', 'cardio', 'employee wellness'] },
  { name: 'activity', label: 'Fitness Metrics', category: 'health', keywords: ['tracker', 'exercise', 'vitals'] },
  { name: 'pill', label: 'Prescription & Pharmacy', category: 'health', keywords: ['pharmacy', 'medicine', 'prescription'] },
  { name: 'stethoscope', label: 'Executive Checkup', category: 'health', keywords: ['physician', 'doctor consult', 'checkup'] },
  { name: 'syringe', label: 'Vaccination & Labs', category: 'health', keywords: ['laboratory', 'vaccine', 'diagnostics'] },
  { name: 'hospital', label: 'Hospitalization Facility', category: 'health', keywords: ['inpatient', 'er', 'hospital admission'] },
  { name: 'cross', label: 'First Aid Clinic', category: 'health', keywords: ['clinic', 'red cross', 'first aid'] },
  { name: 'bandage', label: 'Medical Treatment', category: 'health', keywords: ['wound care', 'treatment'] },
  { name: 'dumbbell', label: 'Gym & Club Membership', category: 'health', keywords: ['fitness membership', 'gym fees', 'workout'] },
  { name: 'smile', label: 'Mental Wellness & EAP', category: 'health', keywords: ['therapy', 'eap', 'counseling', 'mindfulness'] },
  { name: 'brain', label: 'Neurology & Psychology', category: 'health', keywords: ['mental health', 'psychology consult'] },
  { name: 'eye', label: 'Vision & Optical Benefit', category: 'health', keywords: ['eyewear', 'optometry', 'lasik'] },

  // ==========================================
  // 13. WORK & EDUCATION (15+ icons)
  // ==========================================
  { name: 'book', label: 'Books & Reference Manuals', category: 'work', keywords: ['handbook', 'textbook', 'guides'] },
  { name: 'book-open', label: 'Training Course', category: 'work', keywords: ['seminar course', 'workshops', 'training'] },
  { name: 'library', label: 'Knowledge Repository', category: 'work', keywords: ['archive', 'library', 'research'] },
  { name: 'trophy', label: 'Sales Incentive Prize', category: 'work', keywords: ['bonus prize', 'top seller', 'award'] },
  { name: 'medal', label: 'Distinguished Service', category: 'work', keywords: ['merit', 'loyalty award', 'distinction'] },
  { name: 'mail', label: 'Courier & Correspondence', category: 'work', keywords: ['postal', 'formal letter', 'mail courier'] },
  { name: 'inbox', label: 'Accounts Inbox', category: 'work', keywords: ['billing notices', 'inbox', 'incoming bills'] },

  // ==========================================
  // 14. FAMILY & LIFESTYLE (15+ icons)
  // ==========================================
  { name: 'party-popper', label: 'Company Fiesta & Events', category: 'lifestyle', keywords: ['celebration', 'catering', 'annual party'] },
  { name: 'palette', label: 'Creative Arts & Decor', category: 'lifestyle', keywords: ['painting', 'artistic', 'design'] },
  { name: 'paintbrush', label: 'Crafts & Workshops', category: 'lifestyle', keywords: ['maker', 'artisan', 'crafting'] },
  { name: 'music', label: 'Music Streaming', category: 'lifestyle', keywords: ['spotify', 'soundtrack', 'background music'] },
  { name: 'guitar', label: 'Musical Instruments', category: 'lifestyle', keywords: ['instruments', 'band gear'] },
  { name: 'drama', label: 'Theatre & Cultural Events', category: 'lifestyle', keywords: ['shows', 'performing arts', 'tickets'] },
  { name: 'dices', label: 'Team Building & Games', category: 'lifestyle', keywords: ['recreation', 'board games', 'activities'] },

  // ==========================================
  // 15. SYMBOLS & SHAPES (25+ icons)
  // ==========================================
  { name: 'star', label: 'Key Priority Bookmark', category: 'symbols', keywords: ['starred', 'priority', 'favorite'] },
  { name: 'star-half', label: 'Rating & Quality Score', category: 'symbols', keywords: ['rating', 'vendor score', 'performance evaluation'] },
  { name: 'shield', label: 'Risk Protection Guard', category: 'symbols', keywords: ['protection', 'defense', 'shield'] },
  { name: 'flag', label: 'Milestone Marker', category: 'symbols', keywords: ['checkpoint', 'flag', 'status marker'] },
  { name: 'bookmark', label: 'Saved Record', category: 'symbols', keywords: ['saved', 'pinned', 'watchlist'] },
  { name: 'bell', label: 'Reminders & Notifications', category: 'symbols', keywords: ['alarm', 'notice', 'notification'] },
  { name: 'bell-ring', label: 'Urgent Overdue Alarm', category: 'symbols', keywords: ['overdue notice', 'urgent reminder'] },
  { name: 'unlock', label: 'Open Access Account', category: 'symbols', keywords: ['unlocked', 'public access'] },
  { name: 'clock', label: 'Pending Processing', category: 'symbols', keywords: ['duration', 'pending', 'waiting queue'] },
  { name: 'pin', label: 'Pinned Fast Access', category: 'symbols', keywords: ['sticky account', 'pinned pocket'] },
  { name: 'layers', label: 'Multi-Tier Pockets', category: 'symbols', keywords: ['hierarchy', 'sub-accounts', 'tiers'] },
  { name: 'infinity', label: 'Endowment Fund', category: 'symbols', keywords: ['perpetual', 'endless', 'revolving'] },
  { name: 'sliders', label: 'Custom Configuration', category: 'symbols', keywords: ['settings', 'controls', 'parameters'] },
  { name: 'settings', label: 'System Preferences', category: 'symbols', keywords: ['configuration', 'setup', 'gear'] },
  { name: 'refresh-cw', label: 'Automatic Sync Loop', category: 'symbols', keywords: ['auto-debit', 'sync', 'loop'] },
  { name: 'rotate-cw', label: 'Monthly Reset Cycle', category: 'symbols', keywords: ['recurring cycle', 'monthly renewal'] },
  { name: 'check', label: 'Reconciled & Paid', category: 'symbols', keywords: ['settled', 'verified', 'completed check'] },
  { name: 'check-circle-2', label: 'Fully Cleared Account', category: 'symbols', keywords: ['cleared', 'success', 'paid in full'] },
  { name: 'alert-circle', label: 'Discrepancy Notice', category: 'symbols', keywords: ['warning', 'attention needed', 'discrepancy'] },
  { name: 'alert-triangle', label: 'Deficit / Critical Alert', category: 'symbols', keywords: ['overbudget', 'overdue', 'critical deficit'] },
  { name: 'info', label: 'General Information', category: 'symbols', keywords: ['help note', 'guidelines', 'information'] },
  { name: 'help-circle', label: 'Support & Help Desk', category: 'symbols', keywords: ['faq', 'assistance', 'inquiry'] },
  { name: 'circle-dot', label: 'Target Centerpoint', category: 'symbols', keywords: ['bullet', 'focus point', 'center'] },
];

export const ICON_NAMES = ICON_LIBRARY.map(i => i.name);
