import {
  darkShadows,
  lightShadows,
  themeBorderRadius,
  themeSpacing,
  themeTypography,
} from "./foundations";
import { palette } from "./palette";
import type { AppTheme, ThemeColors } from "./theme.types";

const lightCategorical = { ...palette.categorical };
const darkCategorical = {
  blue: "#60A5FA",
  teal: "#2DD4BF",
  green: "#4ADE80",
  lime: "#A3E635",
  amber: "#FBBF24",
  orange: "#FB923C",
  red: "#F87171",
  purple: "#C084FC",
  indigo: "#818CF8",
  pink: "#F472B6",
  slate: "#94A3B8",
} satisfies ThemeColors["categorical"];

function createTheme(
  definition: Pick<AppTheme, "id" | "name" | "description" | "mode" | "colors">,
): AppTheme {
  return {
    ...definition,
    spacing: themeSpacing,
    borderRadius: themeBorderRadius,
    typography: themeTypography,
    shadows: definition.mode === "dark" ? darkShadows : lightShadows,
  };
}

export const paperTheme = createTheme({
  id: "paper",
  name: "Paper",
  description: "Pure white, quiet contrast, and focused green actions.",
  mode: "light",
  colors: {
    background: "#FFFFFF",
    surface: "#F6F7F5",
    surfaceMuted: "#ECEFEB",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#171A18",
    surfaceInverseElevated: "#242825",
    textPrimary: "#171A18",
    textSecondary: "#515A55",
    textMuted: "#6B746F",
    textInverse: "#FFFFFF",
    textInverseMuted: "#C9D0CC",
    border: "#D7DDD9",
    borderStrong: "#AAB5AF",
    primary: "#205F4A",
    onPrimary: "#FFFFFF",
    controlSecondary: "#E6ECE8",
    onControlSecondary: "#173A2E",
    accent: "#B9DB5C",
    onAccent: "#172006",
    focusRing: "#4C8C77",
    success: "#187A4C",
    warning: "#9A5B00",
    danger: "#B42318",
    onDanger: "#FFFFFF",
    info: "#176B87",
    overlay: "rgba(10, 18, 14, 0.48)",
    categorical: lightCategorical,
  },
});

export const inkTheme = createTheme({
  id: "ink",
  name: "Ink",
  description: "True black for OLED screens with soft mint controls.",
  mode: "dark",
  colors: {
    background: "#000000",
    surface: "#0D0F0E",
    surfaceMuted: "#171A18",
    surfaceElevated: "#1F2321",
    surfaceInverse: "#F6F7F5",
    surfaceInverseElevated: "#FFFFFF",
    textPrimary: "#FFFFFF",
    textSecondary: "#B7BDBA",
    textMuted: "#8D9691",
    textInverse: "#171A18",
    textInverseMuted: "#515A55",
    border: "#2A2E2C",
    borderStrong: "#4B524E",
    primary: "#7ED7B3",
    onPrimary: "#062018",
    controlSecondary: "#1F2924",
    onControlSecondary: "#D9E5DF",
    accent: "#D1F26A",
    onAccent: "#172006",
    focusRing: "#A2E6CC",
    success: "#63D69B",
    warning: "#F0B45A",
    danger: "#FF7770",
    onDanger: "#2A0402",
    info: "#72C5E8",
    overlay: "rgba(0, 0, 0, 0.76)",
    categorical: darkCategorical,
  },
});

export const tideTheme = createTheme({
  id: "tide",
  name: "Tide",
  description: "A cool blue-gray workspace with calm, steady contrast.",
  mode: "light",
  colors: {
    background: "#F4F8FA",
    surface: "#FFFFFF",
    surfaceMuted: "#E8F0F3",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#142027",
    surfaceInverseElevated: "#23333C",
    textPrimary: "#142027",
    textSecondary: "#52626A",
    textMuted: "#718089",
    textInverse: "#FFFFFF",
    textInverseMuted: "#CAD7DD",
    border: "#D5E0E5",
    borderStrong: "#AABCC5",
    primary: "#2E6073",
    onPrimary: "#FFFFFF",
    controlSecondary: "#DFEAEE",
    onControlSecondary: "#234A59",
    accent: "#8AC5D5",
    onAccent: "#0B2530",
    focusRing: "#5A91A5",
    success: "#247451",
    warning: "#956000",
    danger: "#B23A32",
    onDanger: "#FFFFFF",
    info: "#176B87",
    overlay: "rgba(10, 25, 33, 0.48)",
    categorical: lightCategorical,
  },
});

export const mossTheme = createTheme({
  id: "moss",
  name: "Moss",
  description: "Soft natural surfaces with grounded evergreen actions.",
  mode: "light",
  colors: {
    background: "#F4F7F2",
    surface: "#FFFFFF",
    surfaceMuted: "#E7EDE4",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#172018",
    surfaceInverseElevated: "#29342B",
    textPrimary: "#172018",
    textSecondary: "#566358",
    textMuted: "#748077",
    textInverse: "#FFFFFF",
    textInverseMuted: "#CDD6CF",
    border: "#D4DED1",
    borderStrong: "#A9BAA6",
    primary: "#3B684A",
    onPrimary: "#FFFFFF",
    controlSecondary: "#E0E9DD",
    onControlSecondary: "#294B34",
    accent: "#B8D98B",
    onAccent: "#1B2D12",
    focusRing: "#6F987A",
    success: "#27774A",
    warning: "#906000",
    danger: "#B23A32",
    onDanger: "#FFFFFF",
    info: "#2F6C7D",
    overlay: "rgba(14, 28, 17, 0.48)",
    categorical: lightCategorical,
  },
});

export const clayTheme = createTheme({
  id: "clay",
  name: "Clay",
  description: "Warm neutral surfaces with restrained terracotta accents.",
  mode: "light",
  colors: {
    background: "#FBF6F3",
    surface: "#FFFFFF",
    surfaceMuted: "#F1E8E3",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#261B17",
    surfaceInverseElevated: "#3A2B25",
    textPrimary: "#261B17",
    textSecondary: "#6A5A53",
    textMuted: "#89776F",
    textInverse: "#FFFFFF",
    textInverseMuted: "#DDCEC7",
    border: "#E5D7D0",
    borderStrong: "#C4AEA4",
    primary: "#875240",
    onPrimary: "#FFFFFF",
    controlSecondary: "#EFE2DC",
    onControlSecondary: "#633C2F",
    accent: "#E7B29E",
    onAccent: "#3B1E14",
    focusRing: "#B47B67",
    success: "#397153",
    warning: "#946000",
    danger: "#AE382F",
    onDanger: "#FFFFFF",
    info: "#376A7B",
    overlay: "rgba(35, 20, 15, 0.48)",
    categorical: lightCategorical,
  },
});

export const duneTheme = createTheme({
  id: "dune",
  name: "Dune",
  description: "Low-glare sand tones for a quiet, paper-like workspace.",
  mode: "light",
  colors: {
    background: "#F8F5EC",
    surface: "#FFFDF8",
    surfaceMuted: "#EEE9DA",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#242219",
    surfaceInverseElevated: "#38352A",
    textPrimary: "#242219",
    textSecondary: "#646052",
    textMuted: "#827C6C",
    textInverse: "#FFFFFF",
    textInverseMuted: "#DAD4C4",
    border: "#DED8C5",
    borderStrong: "#B9B19A",
    primary: "#665F46",
    onPrimary: "#FFFFFF",
    controlSecondary: "#E9E3D2",
    onControlSecondary: "#4C4734",
    accent: "#D8CB86",
    onAccent: "#2C2711",
    focusRing: "#918867",
    success: "#4F7047",
    warning: "#8B620A",
    danger: "#A64235",
    onDanger: "#FFFFFF",
    info: "#496879",
    overlay: "rgba(31, 28, 18, 0.48)",
    categorical: lightCategorical,
  },
});
