import {
  darkShadows,
  lightShadows,
  themeBorderRadius,
  themeSpacing,
  themeTypography,
} from "./foundations";
import { palette } from "./palette";
import type { AppTheme, ThemeColors } from "./theme.types";

const lightCategorical = { ...palette.categorical };
const darkCategorical = {
  blue: "#60A5FA",
  teal: "#2DD4BF",
  green: "#4ADE80",
  lime: "#A3E635",
  amber: "#FBBF24",
  orange: "#FB923C",
  red: "#F87171",
  purple: "#C084FC",
  indigo: "#818CF8",
  pink: "#F472B6",
  slate: "#94A3B8",
} satisfies ThemeColors["categorical"];

function createTheme(
  definition: Pick<AppTheme, "id" | "name" | "description" | "mode" | "colors">,
): AppTheme {
  return {
    ...definition,
    spacing: themeSpacing,
    borderRadius: themeBorderRadius,
    typography: themeTypography,
    shadows: definition.mode === "dark" ? darkShadows : lightShadows,
  };
}

export const paperTheme = createTheme({
  id: "paper",
  name: "Paper",
  description: "Pure white, quiet contrast, and focused green actions.",
  mode: "light",
  colors: {
    background: "#FFFFFF",
    surface: "#F6F7F5",
    surfaceMuted: "#ECEFEB",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#171A18",
    surfaceInverseElevated: "#242825",
    textPrimary: "#171A18",
    textSecondary: "#515A55",
    textMuted: "#6B746F",
    textInverse: "#FFFFFF",
    textInverseMuted: "#C9D0CC",
    border: "#D7DDD9",
    borderStrong: "#AAB5AF",
    primary: "#205F4A",
    onPrimary: "#FFFFFF",
    controlSecondary: "#E6ECE8",
    onControlSecondary: "#173A2E",
    accent: "#B9DB5C",
    onAccent: "#172006",
    focusRing: "#4C8C77",
    success: "#187A4C",
    warning: "#9A5B00",
    danger: "#B42318",
    onDanger: "#FFFFFF",
    info: "#176B87",
    overlay: "rgba(10, 18, 14, 0.48)",
    categorical: lightCategorical,
  },
});

export const inkTheme = createTheme({
  id: "ink",
  name: "Ink",
  description: "True black for OLED screens with soft mint controls.",
  mode: "dark",
  colors: {
    background: "#000000",
    surface: "#0D0F0E",
    surfaceMuted: "#171A18",
    surfaceElevated: "#1F2321",
    surfaceInverse: "#F6F7F5",
    surfaceInverseElevated: "#FFFFFF",
    textPrimary: "#FFFFFF",
    textSecondary: "#B7BDBA",
    textMuted: "#8D9691",
    textInverse: "#171A18",
    textInverseMuted: "#515A55",
    border: "#2A2E2C",
    borderStrong: "#4B524E",
    primary: "#7ED7B3",
    onPrimary: "#062018",
    controlSecondary: "#1F2924",
    onControlSecondary: "#D9E5DF",
    accent: "#D1F26A",
    onAccent: "#172006",
    focusRing: "#A2E6CC",
    success: "#63D69B",
    warning: "#F0B45A",
    danger: "#FF7770",
    onDanger: "#2A0402",
    info: "#72C5E8",
    overlay: "rgba(0, 0, 0, 0.76)",
    categorical: darkCategorical,
  },
});

export const tideTheme = createTheme({
  id: "tide",
  name: "Tide",
  description: "A cool blue-gray workspace with calm, steady contrast.",
  mode: "light",
  colors: {
    background: "#F4F8FA",
    surface: "#FFFFFF",
    surfaceMuted: "#E8F0F3",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#142027",
    surfaceInverseElevated: "#23333C",
    textPrimary: "#142027",
    textSecondary: "#52626A",
    textMuted: "#718089",
    textInverse: "#FFFFFF",
    textInverseMuted: "#CAD7DD",
    border: "#D5E0E5",
    borderStrong: "#AABCC5",
    primary: "#2E6073",
    onPrimary: "#FFFFFF",
    controlSecondary: "#DFEAEE",
    onControlSecondary: "#234A59",
    accent: "#8AC5D5",
    onAccent: "#0B2530",
    focusRing: "#5A91A5",
    success: "#247451",
    warning: "#956000",
    danger: "#B23A32",
    onDanger: "#FFFFFF",
    info: "#176B87",
    overlay: "rgba(10, 25, 33, 0.48)",
    categorical: lightCategorical,
  },
});

export const mossTheme = createTheme({
  id: "moss",
  name: "Moss",
  description: "Soft natural surfaces with grounded evergreen actions.",
  mode: "light",
  colors: {
    background: "#F4F7F2",
    surface: "#FFFFFF",
    surfaceMuted: "#E7EDE4",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#172018",
    surfaceInverseElevated: "#29342B",
    textPrimary: "#172018",
    textSecondary: "#566358",
    textMuted: "#748077",
    textInverse: "#FFFFFF",
    textInverseMuted: "#CDD6CF",
    border: "#D4DED1",
    borderStrong: "#A9BAA6",
    primary: "#3B684A",
    onPrimary: "#FFFFFF",
    controlSecondary: "#E0E9DD",
    onControlSecondary: "#294B34",
    accent: "#B8D98B",
    onAccent: "#1B2D12",
    focusRing: "#6F987A",
    success: "#27774A",
    warning: "#906000",
    danger: "#B23A32",
    onDanger: "#FFFFFF",
    info: "#2F6C7D",
    overlay: "rgba(14, 28, 17, 0.48)",
    categorical: lightCategorical,
  },
});

export const clayTheme = createTheme({
  id: "clay",
  name: "Clay",
  description: "Warm neutral surfaces with restrained terracotta accents.",
  mode: "light",
  colors: {
    background: "#FBF6F3",
    surface: "#FFFFFF",
    surfaceMuted: "#F1E8E3",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#261B17",
    surfaceInverseElevated: "#3A2B25",
    textPrimary: "#261B17",
    textSecondary: "#6A5A53",
    textMuted: "#89776F",
    textInverse: "#FFFFFF",
    textInverseMuted: "#DDCEC7",
    border: "#E5D7D0",
    borderStrong: "#C4AEA4",
    primary: "#875240",
    onPrimary: "#FFFFFF",
    controlSecondary: "#EFE2DC",
    onControlSecondary: "#633C2F",
    accent: "#E7B29E",
    onAccent: "#3B1E14",
    focusRing: "#B47B67",
    success: "#397153",
    warning: "#946000",
    danger: "#AE382F",
    onDanger: "#FFFFFF",
    info: "#376A7B",
    overlay: "rgba(35, 20, 15, 0.48)",
    categorical: lightCategorical,
  },
});

export const duneTheme = createTheme({
  id: "dune",
  name: "Dune",
  description: "Low-glare sand tones for a quiet, paper-like workspace.",
  mode: "light",
  colors: {
    background: "#F8F5EC",
    surface: "#FFFDF8",
    surfaceMuted: "#EEE9DA",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#242219",
    surfaceInverseElevated: "#38352A",
    textPrimary: "#242219",
    textSecondary: "#646052",
    textMuted: "#827C6C",
    textInverse: "#FFFFFF",
    textInverseMuted: "#DAD4C4",
    border: "#DED8C5",
    borderStrong: "#B9B19A",
    primary: "#665F46",
    onPrimary: "#FFFFFF",
    controlSecondary: "#E9E3D2",
    onControlSecondary: "#4C4734",
    accent: "#D8CB86",
    onAccent: "#2C2711",
    focusRing: "#918867",
    success: "#4F7047",
    warning: "#8B620A",
    danger: "#A64235",
    onDanger: "#FFFFFF",
    info: "#496879",
    overlay: "rgba(31, 28, 18, 0.48)",
    categorical: lightCategorical,
  },
});

export const midnightTheme = createTheme({
  id: "midnight",
  name: "Midnight",
  description: "Deep navy surfaces for comfortable low-light and nighttime use.",
  mode: "dark",
  colors: {
    background: "#080D19",
    surface: "#11182A",
    surfaceMuted: "#1A243A",
    surfaceElevated: "#202C46",
    surfaceInverse: "#F5F7FF",
    surfaceInverseElevated: "#FFFFFF",
    textPrimary: "#F7F9FF",
    textSecondary: "#C1C9DA",
    textMuted: "#929DB4",
    textInverse: "#10182A",
    textInverseMuted: "#4D5A73",
    border: "#293653",
    borderStrong: "#4A5C7C",
    primary: "#8AB4FF",
    onPrimary: "#071226",
    controlSecondary: "#1D2C49",
    onControlSecondary: "#DDE7FB",
    accent: "#F6C85F",
    onAccent: "#2A1D00",
    focusRing: "#A9C8FF",
    success: "#62D89B",
    warning: "#F4BF5F",
    danger: "#FF7B7B",
    onDanger: "#310000",
    info: "#78C7FF",
    overlay: "rgba(2, 6, 15, 0.80)",
    categorical: darkCategorical,
  },
});

export const graphiteTheme = createTheme({
  id: "graphite",
  name: "Graphite",
  description: "Neutral dark grays with crisp, distraction-free controls.",
  mode: "dark",
  colors: {
    background: "#111315",
    surface: "#191C1F",
    surfaceMuted: "#24282C",
    surfaceElevated: "#2C3136",
    surfaceInverse: "#F4F5F6",
    surfaceInverseElevated: "#FFFFFF",
    textPrimary: "#F5F6F7",
    textSecondary: "#C2C7CC",
    textMuted: "#969DA4",
    textInverse: "#17191B",
    textInverseMuted: "#51575D",
    border: "#343A40",
    borderStrong: "#596169",
    primary: "#E7E9EB",
    onPrimary: "#17191B",
    controlSecondary: "#2D3338",
    onControlSecondary: "#EEF0F2",
    accent: "#A3E635",
    onAccent: "#172300",
    focusRing: "#C5F36B",
    success: "#68D69A",
    warning: "#F1BE62",
    danger: "#FF7D78",
    onDanger: "#310403",
    info: "#76C8F2",
    overlay: "rgba(0, 0, 0, 0.78)",
    categorical: darkCategorical,
  },
});

export const cobaltTheme = createTheme({
  id: "cobalt",
  name: "Cobalt",
  description: "Focused blue tones for users who prefer a crisp professional workspace.",
  mode: "light",
  colors: {
    background: "#F4F7FC",
    surface: "#FFFFFF",
    surfaceMuted: "#E7EDF7",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#101C35",
    surfaceInverseElevated: "#1C2D50",
    textPrimary: "#101C35",
    textSecondary: "#40506E",
    textMuted: "#657490",
    textInverse: "#FFFFFF",
    textInverseMuted: "#C9D3E8",
    border: "#D4DDEA",
    borderStrong: "#9AAAC4",
    primary: "#174EA6",
    onPrimary: "#FFFFFF",
    controlSecondary: "#DFE8F7",
    onControlSecondary: "#123A78",
    accent: "#73A5FF",
    onAccent: "#071C43",
    focusRing: "#4677C7",
    success: "#18794E",
    warning: "#8A5700",
    danger: "#B3261E",
    onDanger: "#FFFFFF",
    info: "#005EA8",
    overlay: "rgba(8, 21, 48, 0.50)",
    categorical: lightCategorical,
  },
});

export const lavenderTheme = createTheme({
  id: "lavender",
  name: "Lavender",
  description: "Soft violet surfaces for a calm and expressive experience.",
  mode: "light",
  colors: {
    background: "#F8F6FF",
    surface: "#FFFFFF",
    surfaceMuted: "#EEEAF8",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#241A38",
    surfaceInverseElevated: "#382A52",
    textPrimary: "#241A38",
    textSecondary: "#5B506D",
    textMuted: "#7B708C",
    textInverse: "#FFFFFF",
    textInverseMuted: "#DCD3EB",
    border: "#DDD5EA",
    borderStrong: "#B5A8C8",
    primary: "#6750A4",
    onPrimary: "#FFFFFF",
    controlSecondary: "#E8E0F4",
    onControlSecondary: "#4A367B",
    accent: "#D7C4FF",
    onAccent: "#25134D",
    focusRing: "#8B75C2",
    success: "#287852",
    warning: "#8E5A00",
    danger: "#B3263D",
    onDanger: "#FFFFFF",
    info: "#356A9A",
    overlay: "rgba(26, 17, 43, 0.48)",
    categorical: lightCategorical,
  },
});

export const blushTheme = createTheme({
  id: "blush",
  name: "Blush",
  description: "Gentle rose accents for users who enjoy a warmer personal style.",
  mode: "light",
  colors: {
    background: "#FFF7F9",
    surface: "#FFFFFF",
    surfaceMuted: "#F8E8ED",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#321A23",
    surfaceInverseElevated: "#4A2834",
    textPrimary: "#321A23",
    textSecondary: "#6A4E59",
    textMuted: "#8B6D78",
    textInverse: "#FFFFFF",
    textInverseMuted: "#E4CFD7",
    border: "#EAD4DC",
    borderStrong: "#C9A5B1",
    primary: "#8F3F5B",
    onPrimary: "#FFFFFF",
    controlSecondary: "#F3E0E6",
    onControlSecondary: "#683044",
    accent: "#F3B8C8",
    onAccent: "#461323",
    focusRing: "#B76C84",
    success: "#327653",
    warning: "#8D5B00",
    danger: "#B3263D",
    onDanger: "#FFFFFF",
    info: "#326A86",
    overlay: "rgba(45, 18, 28, 0.48)",
    categorical: lightCategorical,
  },
});

export const contrastTheme = createTheme({
  id: "contrast",
  name: "Contrast",
  description: "Strong boundaries and high-contrast text for maximum visual clarity.",
  mode: "light",
  colors: {
    background: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceMuted: "#F0F0F0",
    surfaceElevated: "#FFFFFF",
    surfaceInverse: "#000000",
    surfaceInverseElevated: "#1A1A1A",
    textPrimary: "#000000",
    textSecondary: "#232323",
    textMuted: "#4D4D4D",
    textInverse: "#FFFFFF",
    textInverseMuted: "#D9D9D9",
    border: "#767676",
    borderStrong: "#000000",
    primary: "#0047B3",
    onPrimary: "#FFFFFF",
    controlSecondary: "#E4ECF8",
    onControlSecondary: "#002B70",
    accent: "#FFD600",
    onAccent: "#000000",
    focusRing: "#005FCC",
    success: "#006B3C",
    warning: "#754A00",
    danger: "#A40000",
    onDanger: "#FFFFFF",
    info: "#004E8A",
    overlay: "rgba(0, 0, 0, 0.62)",
    categorical: lightCategorical,
  },
});
